#!/bin/bash
#SBATCH --job-name=gr00t_finetune_gr1_single
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=rlwrld
#SBATCH --output=out/test_%j.out    # %j는 JobID
#SBATCH --error=out/test_%j.err
#SBATCH --comment="GR00T Single Task Finetuning"

##############################
source /virtual_lab/rlwrld/heeseung/miniconda3/etc/profile.d/conda.sh
conda activate gr00t_new
echo "Conda environment 'gr00t_new' activated."


ALL_DATASET_PATHS=(
"/rlwrld/heeseung/datasets/gr1_mg_gr00t_2400"
"/storage2/AgiBotWorld-Beta_lerobot_v2/task_327"
"/storage2/AgiBotWorld-Beta_lerobot_v2/task_351"
"/storage2/AgiBotWorld-Beta_lerobot_v2/task_352"
"/storage2/AgiBotWorld-Beta_lerobot_v2/task_354"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_356"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_357"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_358"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_359"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_360"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_361"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_362"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_363"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_365"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_366"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_367"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_368"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_369"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_372"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_373"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_374"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_375"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_376"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_377"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_378"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_380"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_384"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_385"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_388"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_389"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_390"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_398"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_410"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_421"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_422"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_424"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_425"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_428"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_431"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_433"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_434"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_438"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_440"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_444"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_445"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_446"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_451"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_452"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_453"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_454"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_455"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_460"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_462"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_463"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_464"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_465"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_466"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_468"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_470"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_471"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_474"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_477"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_478"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_480"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_483"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_485"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_486"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_487"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_491"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_492"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_494"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_497"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_498"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_501"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_503"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_504"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_505"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_506"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_507"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_508"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_509"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_511"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_512"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_515"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_520"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_521"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_522"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_524"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_525"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_527"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_528"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_529"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_532"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_533"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_534"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_535"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_537"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_541"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_542"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_543"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_544"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_545"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_550"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_551"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_555"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_556"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_558"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_561"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_563"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_566"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_567"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_568"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_570"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_573"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_574"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_575"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_580"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_582"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_584"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_587"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_588"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_589"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_590"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_593"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_596"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_597"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_598"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_599"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_600"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_602"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_603"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_604"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_607"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_609"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_613"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_616"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_619"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_621"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_658"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_664"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_681"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_682"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_683"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_688"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_689"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_692"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_695"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_698"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_707"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_708"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_709"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_711"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_712"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_714"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_715"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_716"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_717"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_719"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_725"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_726"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_729"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_732"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_734"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_735"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_739"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_740"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_741"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_744"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_748"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_751"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_761"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_762"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_764"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_765"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_773"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_779"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_781"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_782"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_783"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_785"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_786"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_787"
# "/storage2/AgiBotWorld-Beta_lerobot_v2/task_790"
)

# DATA_CONFIGS=(
#   "fourier_gr1_arms_waist"
#   "agibot_beta1"
# )
# EMBODIMENT_TAGS=(
#   "gr1"
#   "new_embodiment"
# )

python /virtual_lab/rlwrld/heeseung/Isaac-GR00T_new/scripts/gr00t_cotrain.py \
  --dataset-path "${ALL_DATASET_PATHS[@]}" \
  --num-gpus 1 --batch-size 16 --learning_rate 1e-4 \
  --output-dir /rlwrld/heeseung/checkpoints/gr00t_agibot_beta_test \
  --data-config agibot_beta1 --embodiment_tag new_embodiment --video_backend torchvision_av \
  --max-steps 1000 --save-steps 1000